const std = @import("std");

pub const core = @import("core/engine.zig");
pub const device = @import("device/device.zig");
pub const mixer = @import("mixer/mixer.zig");
pub const assets = @import("assets/bank.zig");
pub const events = @import("events/runtime.zig");
pub const spatial = @import("spatial/spatial.zig");
pub const acoustic = @import("acoustic/acoustic.zig");
pub const acoustic_production = @import("acoustic/production.zig");
pub const acoustic_gpu_production = @import("acoustic/gpu_production.zig");
pub const runtime = @import("runtime/runtime.zig");

pub const EngineConfig = core.EngineConfig;
pub const Engine = core.Engine;
pub const TelemetrySnapshot = core.TelemetrySnapshot;
pub const BuguError = core.BuguError;
pub const TestVoiceDesc = mixer.TestVoiceDesc;
pub const SampleVoiceDesc = mixer.SampleVoiceDesc;
pub const VoiceHandle = mixer.VoiceHandle;
pub const VoiceControlParams = mixer.VoiceControlParams;
pub const BusId = mixer.BusId;
pub const EffectBusId = mixer.EffectBusId;
pub const EffectBusControlParams = mixer.EffectBusControlParams;
pub const EffectBusSnapshot = mixer.EffectBusSnapshot;
pub const Bank = assets.Bank;
pub const SoundEntry = assets.SoundEntry;
pub const ImportSource = assets.ImportSource;
pub const ImportSummary = assets.ImportSummary;
pub const importToBank = assets.importToBank;
pub const loadBank = assets.loadBank;
pub const EventRuntime = events.EventRuntime;
pub const EventEntry = events.EventEntry;
pub const PostResult = events.PostResult;
pub const AcousticPostResult = events.AcousticPostResult;
pub const AcousticEventInstance = events.AcousticEventInstance;
pub const AcousticLayerHandles = events.AcousticLayerHandles;
pub const PlayEvent = events.PlayEvent;
pub const SwitchEvent = events.SwitchEvent;
pub const SwitchCase = events.SwitchCase;
pub const SoundRef = events.SoundRef;
pub const RtpcCurve = events.RtpcCurve;
pub const hashEventName = events.hashName;
pub const Vec3 = spatial.Vec3;
pub const Transform = spatial.Transform;
pub const AttenuationProfile = spatial.AttenuationProfile;
pub const DistanceCurve = spatial.DistanceCurve;
pub const Cone = spatial.Cone;
pub const SpatialParams = spatial.SpatialParams;
pub const evaluateSpatial = spatial.evaluate;
pub const AcousticResponse = acoustic.AcousticResponse;
pub const AcousticMixerSnapshot = acoustic.AcousticMixerSnapshot;
pub const AcousticMaterial = acoustic.AcousticMaterial;
pub const AcousticPortal = acoustic.AcousticPortal;
pub const AcousticTestScene = acoustic.TestScene;
pub const solveAcoustic = acoustic.solve;
pub const mapAcousticResponseToSnapshot = acoustic.mapResponseToSnapshot;

pub const OfflineBackend = device.OfflineBackend;
pub const MiniaudioBackend = device.MiniaudioBackend;
pub const DeviceConfig = device.DeviceConfig;
pub const ControlRuntime = runtime.ControlRuntime;
pub const RuntimeRenderer = runtime.RuntimeRenderer;
pub const RuntimeInstanceHandle = runtime.InstanceHandle;
pub const RuntimeSampleOwner = runtime.SampleOwner;
pub const RuntimeVoiceParams = runtime.VoiceParams;
pub const RuntimeCompletion = runtime.Completion;
pub const RuntimeOfflineBackend = device.RuntimeOfflineBackend;
pub const RuntimeMiniaudioBackend = device.RuntimeMiniaudioBackend;
pub const RuntimeDeviceState = device.RuntimeDeviceState;
pub const RuntimeDeviceEvidence = device.RuntimeDeviceEvidence;

test {
    std.testing.refAllDecls(@This());
}
